name: Deploy to FTP

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: 'repo' 
    - name: List files after checkout
      run: |
        echo "Contenido de ./repo:"
        ls -la ./repo
        echo "¿Existe .git/?"
        ls -la ./repo/.git/
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: './repo'
        server-dir: ${{ secrets.FTP_DIRECTORY }}  
        exclude: |               
          .git/
          .github/
          README.md
          .ftp-deploy-sync-state.json
