name: Deploy to FTP

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check files to deploy
      run: |
        echo "Contenido del directorio local-dir (./):"
        ls -la
        echo "¿Existe .git/?"
        ls -la .git/
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.FTP_DIRECTORY }}  
        exclude: |               
          .git/
          .github/
          README.md
          .ftp-deploy-sync-state.json
